version: '3.9'
services:
    frontend:
        container_name: docker_test_app_frontend_dev
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - '5173:5173'
        restart: always
        environment:
            - CHOKIDAR_USEPOLLING=true
    backend:
        container_name: docker_test_app_backend
        build: ./backend
        volumes:
            - ./backend:/app
            - /app/.venv
            - /app/__pycache__
        ports:
            - 8080:80
        restart: always
    mariadb:
        container_name: docker_test_app_db
        build: ./db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: kimidori1231!
            MYSQL_USER: docker_test_user
            MYSQL_PASSWORD: kimidori1231!
            MYSQL_DATABASE: docker_test_db
        volumes:
            - ./db/data:/var/lib/mysql
        restart: always
