version: '3.9'
services:
    frontend:
        container_name: docker_test_app_frontend
        build: ./frontend
        ports:
            - '3000:80'
        restart: always
    backend:
        container_name: docker_test_app_backend
        build: ./backend
        ports:
            - 8080:80
        restart: always
    mariadb:
        container_name: docker_test_app_db
        build: ./db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: kimidori1231!
            MYSQL_USER: docker_test_user
            MYSQL_PASSWORD: kimidori1231!
            MYSQL_DATABASE: docker_test_db
        volumes:
            - ./db/data:/var/lib/mysql
        restart: always